name: run-some-check
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths: [ 'docs/**.md' ]
env:
  base_branch: main
  diff_path: 'docs/**.md'
jobs:
  run-some-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch base branch
        run: git fetch origin ${base_branch}:base

      - name: Run some proccesses
        run: |
          diff_files=$(git diff --name-only HEAD base -- "${diff_path}" \
            | tr "\n" " ")
          echo "# diff_files: ${diff_files}"
          ####
          # run some proccesses using ${diff_files}
