name: run-textlint
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths: [ 'docs/**/*.md' ]
    branches: [ main ]
jobs:
  run-textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Git diff
        run: git diff HEAD origin/main
